- name: Copy Metadata Server properties
  template: src={{ tempdir }}/metadata-server.properties.template dest={{ tempdir }}/filled/metadata-server.properties
  delegate_to: localhost

- name: Copy tomcat server.xml
  template: src={{ tempdir }}/server.xml.template dest={{ tempdir }}/filled/server.xml
  delegate_to: localhost

- name: Copy metadata-setenv.sh
  template: src={{ tempdir }}/metadata-setenv.sh.template dest={{ tempdir }}/filled/metadata-setenv.sh
  delegate_to: localhost

- name: Copy log4j.properties
  template: src={{ tempdir }}/log4j.properties.template dest={{ tempdir }}/filled/log4j.properties
  delegate_to: localhost

- name: Copy Metadata server specific keystore
  local_action: copy src={{ conf_root }}/certs/{{ host }}/tomcat_keystore dest={{ tempdir }}/filled/tomcat_keystore


- name: Create filled template tar
  local_action: shell tar -C {{ tempdir }}/filled/ -zvcf {{ tempdir }}/filled_templates.tgz .
  delegate_to: localhost

